<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://restful.cert.org" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://restful.cert.org" xmlns:intf="http://restful.cert.org" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="GetData">

   </wsdl:portType>

   <wsdl:binding name="GetDataSoapBinding" type="impl:GetData">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="GetDataService">

      <wsdl:port binding="impl:GetDataSoapBinding" name="GetData">

         <wsdlsoap:address location="http://localhost:8080/Rest/services/GetData"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
